name = "Kotonoha"
license = "MIT"
licenselink = ""
description = "A simple theme for the Hugo SSG"
homepage = "https://github.com/kamoshi/kotonoha"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Maciej Jur"
  homepage = "https://kamoshi.org"
